{% set name = "snkit" %}
{% set version = "1.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/snkit-{{ version }}.tar.gz
  sha256: e715d608a100f54d888288e15b5a59bfbcecc863684bb47742150dd7e5171e41

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - geopandas >=0.13
    - shapely >=2.0
    - pandas
    - numpy >=1.20
    - pyproj

test:
  imports:
    - snkit
    - snkit.network
  source_files:
    - tests
  requires:
    - pip
    - pytest
    - python {{ python_min }}
  commands:
    - pip check
    - pytest tests

about:
  home: https://github.com/tomalrussell/snkit
  summary: a spatial networks toolkit
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tomalrussell
